apiVersion: v1
kind: Service
metadata:
  namespace: funceasy
  name: gateway
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: gateway
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  namespace: funceasy
  name: gateway-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30123
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: funceasy
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: ziqiancheng/funceasy-gateway
          name: gateway
          env:
            - name: DATA_SOURCE_SERVICE
              value: data-source-service
          ports:
            - containerPort: 8082
          volumeMounts:
            - name: data-source-access
              mountPath: /data_source_access
            - name: gateway-access
              mountPath: /gateway_access
      volumes:
        - name: data-source-access
          secret:
            secretName: data-source-access
        - name: gateway-access
          secret:
            secretName: gateway-access