apiVersion: v1
kind: Service
metadata:
  namespace: funceasy
  name: funceasy-gateway
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: funceasy-gateway
---
apiVersion: v1
kind: Service
metadata:
  namespace: funceasy
  name: funceasy-gateway-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30123
  selector:
    app: funceasy-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: funceasy
  name: funceasy-gateway
spec:
  selector:
    matchLabels:
      app: funceasy-gateway
  template:
    metadata:
      labels:
        app: funceasy-gateway
    spec:
      containers:
        - image: ziqiancheng/funceasy-gateway
          name: funceasy-gateway
          env:
            - name: DATA_SOURCE_SERVICE
              value: data-source-service
            - name: FUNCEASY_GATEWAY_SERVICE_PORT
              value: "8082"
          ports:
            - containerPort: 8082
          volumeMounts:
            - name: data-source-access
              mountPath: /data_source_access
            - name: gateway-access
              mountPath: /gateway_access
      volumes:
        - name: data-source-access
          secret:
            secretName: data-source-access
        - name: gateway-access
          secret:
            secretName: gateway-access